<?php
return [
    'base' => [
        'seoServerURL' => 'https://wptg.wptdata.com',
        'siteConfigServerURL' => 'https://wptg.wptdata.com',
        'log_file' => 'editor_poker_allpost_list.txt',
        'seoCommonFileName' => 'seocommon_poker_article_original.json',
        'database' => 'sitedata.sqlite',
        'imgbb_api_key' => [
            '9fc1b0414d6169d761763120e0b33038',
        ],
        // 顶部导航功能入口（header 模块）：['title' => 名称, 'url' => 入口, 'icon' => bootstrap-icons 类名]
        // 未配置时使用默认值：站点录入 / SEO 报表。新增功能入口只需在此追加一行
        // 'header_modules' => [
        //     ['title' => '站点录入', 'url' => 'siteops.php', 'icon' => 'bi-pencil-square'],
        //     ['title' => 'SEO 报表', 'url' => 'seo_report.php', 'icon' => 'bi-bar-chart-line'],
        //     ['title' => '我的新功能', 'url' => 'new_feature.php', 'icon' => 'bi-star'],
        // ],
    ],
    'gitaccount' => [
        // 'wptcard' => 'wptcard',
        'felangel79' => 'felangel79',
        'andarile' => 'andarile',
        'xpoker79' => 'xpoker79',
        'cdndog' => 'cdndog',
        'wptusa' => 'wptusa',
        'abs1monsters' => 'abs1monsters',
        'abs9906' => 'abs9906',
        'jerryhayes' => 'jerryhayes',
    ],
    'gitserver' => [
        'cloudflare cdndog 8.222.246.123' => '8.222.246.123',
        'cloudflare felangel79 47.251.53.11' => '47.251.53.11',
        'cloudflare andarile79 47.88.54.48' => '47.88.54.48',
        'cloudflare xpoker79 47.251.107.123' => '47.251.107.123',
        'cloudflare wptusa 47.251.90.91' => '47.251.90.91',
        'cloudflare abs1monsters 47.251.160.124' => '47.251.160.124',
        'cloudflare abs9906 47.251.160.124' => '47.251.160.124',
        'cloudflare jerryhayes 47.251.160.124' => '47.251.160.124',
    ],
    'languages' => [
        'en-US' => 'en',
        'ja-JP' => 'ja',
        'zh-CN' => 'zh',
        'zh-TW' => 'tw',
        'zh-HK' => 'hk',
        'es-MX' => 'es',
        'ko-KR' => 'ko',
        'ar-AR' => 'ar',
        'ru-RU' => 'ru',
        'fr-FR' => 'fr',
        'pt-BR' => 'pt',
        'bn-BD' => 'bn',
        'ur-PK' => 'ur',
        'de-DE' => 'de',
        'sv-SE' => 'sv',
        'vi-VN' => 'vi',
        'tr-TR' => 'tr',
        'th-TH' => 'th',
        'en-CA' => 'en',
        'ms-MY' => 'ms',
        'id-ID' => 'id',
        'en-IN' => 'en'
    ],
    'countries' => [
        'en-US' => 'US',
        'ja-JP' => 'JP',
        'zh-CN' => 'CN',
        'zh-TW' => 'TW',
        'zh-HK' => 'HK',
        'es-MX' => 'MX',
        'ko-KR' => 'KR',
        'ar-AR' => 'AR',
        'ru-RU' => 'RU',
        'fr-FR' => 'FR',
        'pt-BR' => 'BR',
        'bn-BD' => 'BD',
        'ur-PK' => 'PK',
        'de-DE' => 'DE',
        'sv-SE' => 'SE',
        'vi-VN' => 'VN',
        'tr-TR' => 'TR',
        'th-TH' => 'TH',
        'en-CA' => 'CA',
        'ms-MY' => 'MY',
        'id-ID' => 'ID',
        'en-IN' => 'IN',
    ],
    'categories' => [
        'article' => 'article',
        'home' => 'home',
        'news' => 'news',
        'blog' => 'blog',
        'game' => 'game'
    ],
    'statuses' => [
        'enable' => 'enable',
        'disable' => 'disable',
        'draft' => 'draft',
        'aidone' => 'aidone',
        'delete' => 'delete'
    ],
    'series' => [
        'poker' => 'poker',
        'story' => 'story',
        'skill' => 'skill',
        'other' => 'other'
    ],
    'pubdir' => [
        'home' => 'home',
        'article' => 'article',
        'pokers' => 'pokers',
        'blog' => 'blog',
        'news' => 'news',
        'faqs' => 'faqs',
        'download' => 'download',
    ],
    'themetype' => [
        'poker' => 'poker',
        'wptgo' => 'wptgo',
        'game' => 'game',
        'casino' => 'casino',
        'movie' => 'movie',
        'toys' => 'toys',
    ],
    'sitetype' => [
        'traffic' => 'traffic',
        'cta' => 'cta',
        'purecta' => 'purecta',
    ]
];