<?php
return [
    'base' => [
        'seoServerURL' => 'https://wptg.wptdata.com',
        'siteConfigServerURL' => 'https://wptg.wptdata.com',
        'log_file' => 'editor_poker_allpost_list.txt',
        'log_files' => ['editor_okx_allpost_list.txt', 'editor_poker_allpost_list.txt'],
        'seoCommonFileName' => 'seocommon_poker_article_original.json',
        'database' => 'sitedata.sqlite',
        'imgbb_api_key' => [
            '9fc1b0414d6169d761763120e0b33038',
            '2b3203a4aacf4c6927e4a9689d471b8a',
            'd33c0e89e302966a26575933770e33ae',
            'a54b7c1b78bb518448362a58e8ad6b9c',
            '3cbd619915a2a66dad22488691a1468d',
            'ff808c1643a3566fe6f9e6c506aa70f3',
        ],
        // 静态 API CSRF token：curl/脚本调用时可携带 csrf_token=xxx（POST 字段或 X-CSRF-Token 头）绕过浏览器 cookie 校验。
        // 未配置（留空/注释）时所有入口维持原有行为；配置后所有入口（含页面与任务脚本）要求有效 token 或已登录会话（git 服务器 IP 白名单除外）。
        // 每个值应为高熵随机串，用 curl -d "csrf_token=your-long-random-token-here" 或 -H "X-CSRF-Token: your-long-random-token-here" 访问
        'api_csrf_tokens' => [
            'replace-with-a-long-random-token',
        ],
        // 顶部导航功能入口（header 模块）：['title' => 名称, 'url' => 入口, 'icon' => bootstrap-icons 类名]
        // 未配置时使用默认值：站点录入 / SEO 报表。新增功能入口只需在此追加一行
        // 'header_modules' => [
        //     ['title' => '站点录入', 'url' => 'siteops.php', 'icon' => 'bi-pencil-square'],
        //     ['title' => 'SEO 报表', 'url' => 'seo_report.php', 'icon' => 'bi-bar-chart-line'],
        //     ['title' => '我的新功能', 'url' => 'new_feature.php', 'icon' => 'bi-star'],
        // ],
    ],
    'gitaccount' => [
        // 'wptcard' => 'wptcard',
        'felangel79' => 'felangel79',
        'andarile' => 'andarile',
        'xpoker79' => 'xpoker79',
        'cdndog' => 'cdndog',
        'wptusa' => 'wptusa',
        'abs1monsters' => 'abs1monsters',
        'abs9906' => 'abs9906',
        'jerryhayes' => 'jerryhayes',
    ],
    'gitserver' => [
        'cloudflare cdndog 8.222.246.123' => '8.222.246.123',
        'cloudflare felangel79 47.251.53.11' => '47.251.53.11',
        'cloudflare andarile79 47.88.54.48' => '47.88.54.48',
        'cloudflare xpoker79 47.251.107.123' => '47.251.107.123',
        'cloudflare wptusa 47.251.90.91' => '47.251.90.91',
        'cloudflare abs1monsters 47.251.160.124' => '47.251.160.124',
        'cloudflare abs9906 47.251.160.124' => '47.251.160.124',
        'cloudflare jerryhayes 47.251.160.124' => '47.251.160.124',
    ],
    'languages' => [
        'en-US' => 'en',
        'ja-JP' => 'ja',
        'zh-CN' => 'zh',
        'zh-TW' => 'tw',
        'zh-HK' => 'hk',
        'es-MX' => 'es',
        'ko-KR' => 'ko',
        'ar-AR' => 'ar',
        'ru-RU' => 'ru',
        'fr-FR' => 'fr',
        'pt-BR' => 'pt',
        'bn-BD' => 'bn',
        'ur-PK' => 'ur',
        'de-DE' => 'de',
        'sv-SE' => 'sv',
        'vi-VN' => 'vi',
        'tr-TR' => 'tr',
        'th-TH' => 'th',
        'en-CA' => 'en',
        'ms-MY' => 'ms',
        'id-ID' => 'id',
        'en-IN' => 'en'
    ],
    'translateto' => [
        'en' => '🇺🇸 en (English)',
        'ja' => '🇯🇵 ja (日本語)',
        'zh' => '🇨🇳 zh (简体中文)',
        'tw' => '🇹🇼 tw (繁體中文)',
        'hk' => '🇭🇰 hk (香港中文)',
        'es' => '🇪🇸 es (Español)',
        'ko' => '🇰🇷 ko (한국어)',
        'ar' => '🇸🇦 ar (العربية)',
        'ru' => '🇷🇺 ru (Русский)',
        'fr' => '🇫🇷 fr (Français)',
        'mx' => '🇲🇽 mx (Es - México)',
        'br' => '🇧🇷 br (Pt - Brasil)',
        'bn' => '🇧🇩 bn (বাংলা)',
        'ur' => '🇵🇰 ur (اردو)',
        'de' => '🇩🇪 de (Deutsch)',
        'sv' => '🇸🇪 sv (Svenska)',
        'vi' => '🇻🇳 vi (Tiếng Việt)',
        'tr' => '🇹🇷 tr (Türkçe)',
        'th' => '🇹🇭 th (ไทย)',
    ],
    'countries' => [
        'en-US' => 'US',
        'ja-JP' => 'JP',
        'zh-CN' => 'CN',
        'zh-TW' => 'TW',
        'zh-HK' => 'HK',
        'es-MX' => 'MX',
        'ko-KR' => 'KR',
        'ar-AR' => 'AR',
        'ru-RU' => 'RU',
        'fr-FR' => 'FR',
        'pt-BR' => 'BR',
        'bn-BD' => 'BD',
        'ur-PK' => 'PK',
        'de-DE' => 'DE',
        'sv-SE' => 'SE',
        'vi-VN' => 'VN',
        'tr-TR' => 'TR',
        'th-TH' => 'TH',
        'en-CA' => 'CA',
        'ms-MY' => 'MY',
        'id-ID' => 'ID',
        'en-IN' => 'IN',
    ],
    'categories' => [
        'article' => 'article',
        'home' => 'home',
        'news' => 'news',
        'blog' => 'blog',
        'game' => 'game'
    ],
    'statuses' => [
        'enable' => 'enable',
        'disable' => 'disable',
        'draft' => 'draft',
        'aidone' => 'aidone',
        'delete' => 'delete'
    ],
    'series' => [
        'poker' => 'poker',
        'story' => 'story',
        'skill' => 'skill',
        'other' => 'other'
    ],
    'pubdir' => [
        'home' => 'home',
        'article' => 'article',
        'pokers' => 'pokers',
        'blog' => 'blog',
        'news' => 'news',
        'faqs' => 'faqs',
        'download' => 'download',
    ],
    'themetype' => [
        'poker' => 'poker',
        'wptgo' => 'wptgo',
        'game' => 'game',
        'casino' => 'casino',
        'movie' => 'movie',
        'toys' => 'toys',
    ],
    'sitetype' => [
        'traffic' => 'traffic',
        'cta' => 'cta',
        'purecta' => 'purecta',
    ]
];